package.json, src/features/vote/ActiveRequests.tsx, src/features/vote/ActiveRequestsForm.tsx, src/features/vote/PastRequests.tsx, src/features/vote/Vote.tsx, src/features/vote/helpers/formatPastRequestByAddress.ts, src/features/wallet/Wallet.tsx, src/features/wallet/helpers/calculateUMATotalValue.ts, src/features/wallet/helpers/checkAvailableRewards.ts, src/features/wallet/helpers/collectRewards.ts, src/features/wallet/helpers/formatWalletBalance.ts, src/features/wallet/styled/Wallet.styled.tsx, src/hooks/index.ts, src/hooks/useMulticall.ts, src/hooks/useVotesRevealedEvents.ts, src/web3/createMulticallContractInstance.ts, src/web3/createVotingContractInstance.ts, src/web3/get/queryGetPendingRequests.ts, src/web3/get/queryRetrieveRewards.ts, src/web3/get/queryRewardsRetrievedEvents.ts, src/web3/get/queryVotesRevealedEvents.ts, src/web3/post/retrieveRewards.ts, yarn.lock
**Motivation**
Voter should be able to collect all rewards available to them after round ends.
**Summary**
User may click the "collect" button on the wallet section if rewards are available; this will trigger a request to their wallet.
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> feat: retrieve all rewards works 

src/hooks/useEncryptedVotesEvents.ts
=> encrypted vote checks for PK

src/App.tsx, src/Providers.tsx, src/common/components/navbar/Navbar.tsx, src/common/context/OnboardContext.tsx, src/common/hooks/useOnboard.ts, src/features/router/Router.tsx, src/features/vote/CommitPhase.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/Vote.tsx, src/features/vote/helpers/formatPastRequestByAddress.ts, src/features/vote/helpers/formatPastRequestsNoAddress.ts, src/features/vote/styled/ActiveRequests.styled.tsx, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/useTableValues.ts, src/features/wallet/Wallet.tsx, src/features/wallet/helpers/calculateUMATotalValue.ts, src/features/wallet/helpers/formatWalletBalance.ts, src/features/wallet/helpers/shortenAddress.ts, src/features/wallet/styled/Wallet.styled.tsx, src/hooks/usePendingRequests.ts, src/hooks/useRewardsRetrievedEvents.ts, src/index.tsx, src/web3/get/queryRewardsRetrievedEvents.ts
**Motivation**
On account change, app needs to handle balance changing more gracefully. 
**Summary**
-Onboard properly disconnects now, using a ref in the hook.
-Balances update properly when swapping between accounts.
-Various tiny UI fixes (had duplicate snapshot bug); Minor fix to null in past requests.
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> feat: App handles MM account changes more gracefully.

src/features/vote/ActiveRequests.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/Vote.tsx, src/features/vote/useTableValues.ts, src/features/wallet/TwoKeyContractModal.tsx, src/hooks/useEncryptedVotesEvents.ts, src/web3/get/queryEncryptedVotesEvents.ts
BUG FIX: Reference hot address for events for new signing key method.
=> Optional text to modal.

src/App.tsx, src/features/router/Router.tsx, src/features/vote/ActiveRequests.tsx, src/features/vote/ActiveViewDetailsModal.tsx, src/features/vote/CommitPhase.tsx, src/features/vote/PastViewDetailsModal.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/SubmitCommitsModal.tsx, src/features/vote/Vote.tsx, src/features/vote/fetchUMIP.ts, src/features/vote/helpers/calculateTimeRemaining.ts, src/features/vote/helpers/formatPastRequestsNoAddress.ts, src/features/vote/styled/DetailModals.styled.tsx, src/features/vote/styled/RevealPhase.styled.tsx, src/features/vote/styled/SubmitCommitsModal.styled.tsx, src/features/vote/useTableValues.ts, src/features/vote/useUMIP.ts, src/features/wallet/TwoKeyContractModal.tsx, src/features/wallet/Wallet.tsx, src/features/wallet/styled/TwoKeyContractModal.styled.tsx, src/features/wallet/styled/Wallet.styled.tsx, src/hooks/index.ts, src/hooks/useVotingAddress.ts, src/web3/post/commitVotes.ts
following have been addressed:
https://app.clubhouse.io/uma-project/story/832/denote-countdown-timer-in-hours-h-and-minutes-m
https://app.clubhouse.io/uma-project/story/833/when-you-click-on-the-settings-wheel-and-your-two-wallet-addresses-comes-up-call-the-cold-wallet-the-designatedvoting-wallet
https://app.clubhouse.io/uma-project/story/823/ui-issues-when-rejecting-transactions
https://app.clubhouse.io/uma-project/story/836/when-wallet-is-not-connected-show-instead-of-0-for-all-the-balances-in-wallet-module
https://app.clubhouse.io/uma-project/story/837/when-wallet-is-not-connected-show-display-for-the-vote-status
https://app.clubhouse.io/uma-project/story/844/style-alignment-issue-on-reveal
https://app.clubhouse.io/uma-project/story/846/formatting-issue-on-modal …
=> Feat: Various text fixes

src/features/vote/CommitPhase.tsx, src/features/vote/helpers/formatVoteDataToCommit.ts, src/features/vote/useTableValues.ts, src/web3/get/queryEncryptedVotesEvents.ts, src/web3/get/queryGetPendingRequests.ts
=> fixed issue with recommit.

.circleci/config.yml
Start basic configs to use circleCI on the repo.
=> improve (CircleCI): Add ci file bootstrap

.circleci/config.yml
Signed-off-by: uma-mining <contato@evaldofelipe.com>
=> Fix (CircleCI): Environment vars

src/features/vote/styled/DetailModals.styled.tsx, src/features/wallet/styled/TwoKeyContractModal.styled.tsx
Had two scrollbars in the modal due to incorrect css.
=> Bug: modal scroll fix.

.circleci/config.yml
Signed-off-by: uma-mining <contato@evaldofelipe.com>
=> Fix (CircleCI): Variable type

src/features/vote/CommitPhase.tsx, src/features/vote/SubmitCommitsModal.tsx, src/features/vote/styled/SubmitCommitsModal.styled.tsx
1) Commit modal flow closes and leverage Notify.js only.
2) Removed reference to modal state.
=> feat: Adjust commit modal flow

src/common/components/modal/Modal.tsx, src/common/components/text-input/TextInput.tsx, src/common/helpers/formatPriceRequestVoteData.ts, src/features/vote/ActiveRequests.tsx, src/features/vote/ActiveViewDetailsModal.tsx, src/features/vote/CommitPhase.tsx, src/features/vote/PastRequests.tsx, src/features/vote/PastViewDetailsModal.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/fetchUMIP.ts, src/features/vote/helpers/formatPastRequestByAddress.ts, src/features/vote/helpers/formatPastRequestsNoAddress.ts, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/DetailModals.styled.tsx, src/features/vote/useUMIP.ts, src/features/wallet/helpers/createDesignatedVotingContract.ts
Implementations of these two tickets:
1) General adjustments to view details modal. https://app.clubhouse.io/uma-project/story/974/misc-adjustments-to-view-details-module
2) Input now has validation to check for numbers. Shows error, prevents summary modal from opening. https://app.clubhouse.io/uma-project/story/975/voter-should-not-be-able-to-enter-non-numeric-values-into-the-voter-dapp-fields-for-numeric-price-requests
=> feat: improved details in active details modal; commit input now has validation

.circleci/config.yml
Signed-off-by: uma-mining <contato@evaldofelipe.com>
=> Fix (CircleCI): Remove deployment job

src/features/vote/CommitPhase.tsx, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/RevealPhase.styled.tsx
Regexp was too strict, need to allow Admin votes.
=> bug: hotfix for regexp

src/common/apollo/client.ts
=> updated thegraph url.

src/App.tsx, src/common/hooks/useOnboard.ts, src/features/vote/ActiveViewDetailsModal.tsx, src/features/vote/CommitPhase.tsx, src/features/vote/UpcomingRequests.tsx, src/features/vote/fetchUMIP.ts, src/features/vote/styled/ActiveRequests.styled.tsx, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/DetailModals.styled.tsx, src/features/vote/styled/PastRequests.styled.tsx, src/features/vote/styled/UpcomingRequests.styled.tsx, src/features/vote/useTableValues.ts, src/features/vote/useUMIP.ts, src/features/wallet/Wallet.tsx, src/features/wallet/styled/Wallet.styled.tsx
**Motivation**
Various small CSS bug fixes, minor adjustments to text.
**Details**
1. Further clarification on css polish, cleared by Tom. https://app.clubhouse.io/uma-project/story/1232/mimic-minor-elements-in-initial-design
2. Anc data in modal doesn't show if it equals "0x". (https://app.clubhouse.io/uma-project/story/1276/do-not-show-ancillary-data-if-there-is-no-ancillary-data-to-show)
3. Minor cleaning to wallet module (https://app.clubhouse.io/uma-project/story/1287/wallet-module-should-match-figma)
4. Description truncates now by character, as requested. at >255 characters, Read More will show up. (https://app.clubhouse.io/uma-project/story/1284/align-text-in-the-description-to-show-the-same-number-of-characters-in-each-vote)
5. Changed UMIP type include umipLink, not url …
=> Bugs: Css bug fixes

src/App.tsx, src/common/components/navbar/Navbar.tsx, src/features/vote/ActiveRequests.tsx, src/features/vote/CommitPhase.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/SubmitCommitsModal.tsx, src/features/vote/styled/SubmitCommitsModal.styled.tsx, src/features/wallet/TwoKeyContractModal.tsx, src/features/wallet/Wallet.tsx, src/features/wallet/styled/TwoKeyContractModal.styled.tsx
Features as discussed in earlier morning meeting as requirements for public app release.
=> feat: Sign message equivalent to old voter dapp. Added voting address to modal.

src/common/components/footer/Footer.tsx, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/RevealPhase.styled.tsx
Button wrapper has a max width of 1400px to align better. Changed footer link as requested.
=> bug: Button misplacement; changed footer link

.circleci/config.yml
Signed-off-by: uma-mining <contato@evaldofelipe.com>
=> Increase docker size

src/features/vote/ActiveRequests.tsx, src/features/vote/ActiveViewDetailsModal.tsx, src/features/vote/RevealPhase.tsx, src/features/vote/Vote.tsx, src/hooks/index.ts, src/hooks/useVotesCommittedEvents.ts, src/hooks/useVotesRevealedEventsSummary.ts
Voter summary stats added to commit and reveal modals: (https://app.clubhouse.io/uma-project/story/1278/add-vote-statistics)
=> feat: Voter stats in reveal and commit modal.

src/common/components/footer/Footer.styled.tsx, src/common/components/footer/Footer.tsx, src/common/components/modal/Modal.tsx, src/common/components/navbar/Navbar.styled.tsx, src/common/components/navbar/Navbar.tsx, src/features/vote/SubmitCommitsModal.tsx, src/features/vote/styled/ActiveRequests.styled.tsx, src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/PastRequests.styled.tsx, src/features/vote/styled/RevealPhase.styled.tsx, src/features/vote/styled/SubmitCommitsModal.styled.tsx, src/features/wallet/styled/Wallet.styled.tsx, yarn.lock
Improvements to overall responsiveness of voter-dapp.
https://app.clubhouse.io/uma-project/story/1632/fix-the-module-for-committing-votes-on-mobile
=> Responsive minor update

src/features/vote/helpers/formatPastRequestByAddress.ts, src/features/vote/helpers/formatPastRequestsNoAddress.ts
=> fix: Fixed precision for old price.

src/features/vote/PastViewDetailsModal.tsx
**Motivation**
Adds UMIP link to past request modal
https://app.clubhouse.io/uma-project/story/2005/link-to-umip-is-not-properly-connected-to-cms
**Testing**
Check a box to describe how you tested these changes and list the steps for reviewers to test.
=> fix(voter-dapp): add umip link to past requests

src/common/components/footer/Footer.tsx
=> removed risk labs.

src/common/apollo/queries.ts
GraphQL query properly formatted, returns latest proposals.
=> fix: fixed issue with graphql query.

src/features/vote/helpers/formatVoteDataToCommit.ts
Signed-off-by: david <david@umaproject.org>
=> fix: fix committing when anc data fails to decode

src/features/vote/useTableValues.ts
Fixes reveal issue with anc data that's not UTF-8.
=> fix: don't convert anc data. Reference ancHex

vercel.json
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Add headers

src/features/vote/styled/CommitPhase.styled.tsx, src/features/vote/styled/PastRequests.styled.tsx, src/features/wallet/styled/TwoKeyContractModal.styled.tsx, src/features/wallet/styled/Wallet.styled.tsx
Signed-off-by: david <david@umaproject.org>
=> fix: change scroll to auto

src/common/components/modal/Modal.tsx, src/features/vote/styled/DetailModals.styled.tsx
Signed-off-by: david <david@umaproject.org>
=> fix: make modal scroll auto

src/features/vote/styled/ActiveRequests.styled.tsx, src/features/vote/styled/PastRequests.styled.tsx, src/features/vote/styled/UpcomingRequests.styled.tsx
=> fix: border-spacing

src/common/utils/format.ts, src/features/vote/PastRequests.tsx, src/features/vote/styled/PastRequests.styled.tsx
=> fix: limit width of vote TD.

src/features/vote/styled/ActiveRequests.styled.tsx
=> fix: wrapping styling on reveal/commit

src/features/vote/CommitPhase.tsx
Story details: https://app.shortcut.com/uma-project/story/5323
=> feat: Add a check in the voterdapp to make sure people cant submit a positive magic number

package.json, src/App.tsx, src/common/apollo/queries.ts, src/common/components/navbar/Navbar.styled.tsx, src/common/components/navbar/Navbar.tsx, src/common/helpers/formatPriceRequestVoteData.ts, src/common/hooks/useVoteData.ts, src/features/router/Router.tsx, src/features/vote/PastRequests.tsx, src/features/vote/Vote.tsx, src/features/vote/helpers/formatPastRequestByAddress.ts, yarn.lock
Past Requests now show rewards calculation without revealing from GraphQL data.
=> feat: show rewards in column without revealing in Past Requests
